version: '3.4'

x-logging: &default-logging
  options:
    max-size: '500m'
    max-file: '1'
  driver: json-file

services:
  kafka:
    image: catenae/kafka
    volumes:
      - ./config/server.properties:/opt/kafka/default/config/server.properties:ro
      - ./data:/opt/kafka/default/logs
  logging: *default-logging
